name: Check Passwall Changes

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set variables
      run: |
        echo "BUILDTIME=$(TZ=Asia/Jakarta date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
      shell: bash
      
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: 'dev'

    - name: Delete luci-app-passwall2 if changes detected
      run: |
        rm -rf luci-app-passwall2

    - name: Clone passwall repo and overwrite .github folder
      run: |
        mkdir backup
        cp .github/workflows/Auto\ Update.yaml backup/
        git clone --depth=1 https://github.com/xiaorouji/openwrt-passwall2.git
        mv openwrt-passwall2/luci-app-passwall2 .
        rsync -av --delete openwrt-passwall2/.github/ ./.github/
        cp backup/Auto\ Update.yaml .github/workflows/
        rm -rf openwrt-passwall2 backup

    - uses: stefanzweifel/git-auto-commit-action@v5
      id: auto-commit-action
      with:
       commit_message: "🎉 Sync: ${{ env.BUILDTIME }}"

    - name: pull-request-action
      uses: vsoch/pull-request-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_BRANCH: "main"
