name: Check Passwall Changes

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set variables
      run: |
        echo "BUILDTIME=$(TZ=Asia/Jakarta date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
      shell: bash
      
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: 'dev'

    - name: Delete luci-app-passwall2 if changes detected
      run: |
        rm -rf luci-app-passwall2

    - name: Clone passwall repo and overwrite .github folder
      run: |
        mkdir backup
        cp .github/workflows/Auto\ Update.yaml backup/
        git clone --depth=1 https://github.com/xiaorouji/openwrt-passwall2.git
        mv openwrt-passwall2/luci-app-passwall2 .
        rsync -av --delete openwrt-passwall2/.github/ ./.github/
        cp backup/Auto\ Update.yaml .github/workflows/
        rm -rf openwrt-passwall2 backup

    - uses: stefanzweifel/git-auto-commit-action@v5
      id: auto-commit-action
      with:
       commit_message: "🎉 Sync: ${{ env.BUILDTIME }}"

    - name: Create Pull Request
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      uses: actions/github-script@v4
      with:
        script: |
          const github = require('@actions/github');
          const context = github.context;

          const token = process.env.GITHUB_TOKEN;
          const octokit = github.getOctokit(token);

          const newBranchName = `update-luci-app-passwall2-${Date.now()}`;

          octokit.repos.createOrUpdateFileContents({
            owner: context.repo.owner,
            repo: context.repo.repo,
            path: '.github/workflows/Auto Update.yaml',
            message: 'Update luci-app-passwall2',
            content: Buffer.from('Update luci-app-passwall2').toString('base64'),
            branch: newBranchName
          });
